name: Generate Alerts

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      ENROLLSYS_API: ${{ secrets.ENROLLSYS_API }}
      ENROLLSYS_API_KEY: ${{ secrets.ENROLLSYS_API_KEY }}
      EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
      EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
      EMAILJS_PRIVATE_KEY: ${{ secrets.EMAILJS_PRIVATE_KEY }}
      POLL_INTERVAL: 300000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run alert script
        run: node index.js
